### ISSUE TITLE
Background Job with tsed services and models

### ISSUE THREAD

**Issue by sasidhar-d** [Romakita/ts-express-decorators#452]
## Informations

Type | Version
---|---
Question | 4.x

****

## Description
I need to run a background job at a specific time everyday. I have all the application logic written using tsed. I want to write a crontab to execute a task daily and I am trying to invoke one of the services directly from node command line. But I can't seem to figure out how to import all necessary dependencies without injecting them (which I can't because the node process has to be called from command line outside express execution environment).

Even if I can get the models (@tsed/mongoose) to work, I would be good to go. Am I doing this wrong? Is there a better way to do this?

Thanks.

**Comment by sasidhar-d** [comment]
Hey @Romakita 
Thanks for the quick reply. I followed your approach and I wrote two files as follows:

`main.service.ts`

```
import { Service } from "@tsed/common";
import { BookingService } from "../bookings/bookings.service";

@Service()
export class MainBackgroundService {
  constructor(private bookingService: BookingService) {}
  async doSomething() {
    console.log("now I can do background job stuff");
    await this.bookingService.trialAddAsset();
  }
}
```

`cron.service.ts`
```

import { InjectorService } from "@tsed/common";
import { MainBackgroundService } from "./main.service";

class CronService {
  async doStuff() {
    const injector = new InjectorService();
    injector.load();
    const cronService: any = injector.invoke(MainBackgroundService);
    await cronService.doSomething();
    console.log("done doing sample");
  }
}
new CronService().doStuff();


```
The `trialAddAsset` is supposed to insert a sample document into the database. I am invoking the cron.service with the command `node ./build/src/services/background-jobs/cron.service.js`
I see the following problems with the it so far:

1. The process never exits
2. I don't see how the process is going to pick up the database connection. How should I tell the process where the db is, its port, dbname and all those stuff?
3. May be because of point 2 I am nothing gets saved to the Database.
4. I am always getting the following error:
```
(node:79914) UnhandledPromiseRejectionWarning: INJECTION_ERROR: Service ControllerService > ExpressApplication not found.    at Function.mapServices (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/@tsed/src/common/di/services/InjectorService.ts:286:19)
    at designParamTypes.map (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/@tsed/src/common/di/services/InjectorService.ts:257:22)
    at Array.map (<anonymous>)
    at Function.invoke (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/@tsed/src/common/di/services/InjectorService.ts:256:14)
    at container.forEach (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/@tsed/src/common/di/services/InjectorService.ts:496:50)
    at Map.forEach (<anonymous>)
    at Function.build (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/@tsed/src/common/di/services/InjectorService.ts:483:14)
    at Function.<anonymous> (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/@tsed/src/common/di/services/InjectorService.ts:468:14)
    at Generator.next (<anonymous>)
    at /Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/tslib/tslib.js:103:16)
    at Function.load (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/@tsed/common/lib/di/services/InjectorService.js:363:24)
    at Object.<anonymous> (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/src/plugins/audit.plugin.ts:8:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
(node:79914) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, orby rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:79914) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:79914) UnhandledPromiseRejectionWarning: INJECTION_ERROR: Service ControllerService > ExpressApplication not found.
    at Function.mapServices (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/@tsed/src/common/di/services/InjectorService.ts:286:19)
    at designParamTypes.map (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/@tsed/src/common/di/services/InjectorService.ts:257:22)
    at Array.map (<anonymous>)
    at Function.invoke (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/@tsed/src/common/di/services/InjectorService.ts:256:14)
    at container.forEach (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/@tsed/src/common/di/services/InjectorService.ts:496:50)
    at Map.forEach (<anonymous>)
    at Function.build (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/@tsed/src/common/di/services/InjectorService.ts:483:14)
    at Function.<anonymous> (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/@tsed/src/common/di/services/InjectorService.ts:468:14)
    at Generator.next (<anonymous>)
    at /Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/tslib/tslib.js:103:16)
    at Function.load (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/@tsed/common/lib/di/services/InjectorService.js:363:24)
    at InjectorService.<anonymous> (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/@tsed/src/common/di/services/InjectorService.ts:217:32)
    at Generator.next (<anonymous>)
    at /Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/tslib/tslib.js:107:75
(node:79914) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, orby rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:79914) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'save' of undefined
    at Object.<anonymous> (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/src/plugins/audit.plugin.ts:18:24)
    at Generator.next (<anonymous>)
    at /Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/build/src/plugins/audit.plugin.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/build/src/plugins/audit.plugin.js:3:12)
    at logAction (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/src/plugins/audit.plugin.ts:13:79)
    at Object.<anonymous> (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/src/plugins/audit.plugin.ts:22:11)
    at Generator.next (<anonymous>)
    at /Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/build/src/plugins/audit.plugin.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/build/src/plugins/audit.plugin.js:3:12)
    at model.schema.pre (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/src/plugins/audit.plugin.ts:21:35)
    at callMiddlewareFunction (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/kareem/index.js:399:23)
    at model.next (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/kareem/index.js:58:7)
    at _next (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/kareem/index.js:106:10)
    at process.nextTick (/Users/sasidhardwadasi/Documents/sasi/personal/league-ally/kemper-arena-api/node_modules/kareem/index.js:424:38)
(node:79914) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, orby rejecting a promise which was not handled with .catch(). (rejection id: 6)
```

How do I get around these stuff?

Thanks,
Sasidhar

**Comment by Romakita** [comment]
Ho shit...ok the simpliest way is to use the loadInjector function from`@tsed/testing` as example. 

https://github.com/Romakita/ts-express-decorators/blob/v4.31.5/packages/testing/loadInjector.ts

```typescript
import { loadInjector } from "@tsed/testing";
import { MainBackgroundService } from "./main.service";

class CronService {
  async doStuff() {
    const injector = loadInjector()
    
    const cronService: any = injector.invoke(MainBackgroundService);
    await cronService.doSomething();
    console.log("done doing sample");
  }
}
new CronService().doStuff();
```
It should works ;)

**Comment by sasidhar-d** [comment]
@Romakita 
I am getting the following error:
```
error TS2305: Module '"/path/node_modules/@tsed/testing/lib/index"' has no exported member 'loadInjector'.
```

**Comment by Romakita** [comment]
Hello,
I've right. I've added the loadInjector() to the export. 

> But it still doesn't affect the DB. I do await model.save() and it never returns.
Yes... that means, the connection isn't established, because, the server isn't initialized (Server [Lifecycle](http://tsed.io/docs/server-loader.html#lifecycle-hooks)). Sorry I thinks I give you the bad process to run your service, because, you need the Server configuration and run process to mount correctly your database.

Ok here is the right process. Create a CronServer.ts file on same level of your Server.ts and copy this code:
```typescript
import {Server} from "./Server";

export class CronServer extends Server { // I'm not sure if you have to put @ServerSettings here. Try and tell me if it works without
    async start() {
         const start = new Date();
         try {
             await this.loadSettingsAndInjector();

             await this.injector.emit("$onCronReady"); // create a custom hook (event) for your services

             $log.info(`Started in ${new Date().getTime() - start.getTime()} ms`);
        } catch (err) {
             this.callHook("$onServerInitError", undefined, err);
             return Promise.reject(err);
        }
    } 
} 
```
Now you CronServer is ready. You can implement $onCronReady hook on any services.

```typescript
import { Service } from "@tsed/common";
import { BookingService } from "../bookings/bookings.service";

@Service()
export class MainBackgroundService {
  constructor(private bookingService: BookingService) {}
  async $onCronReady() {
    console.log("now I can do background job stuff");
    await this.bookingService.trialAddAsset();
  }
}
```
> Note: You can implement $onCronReady directly on BookingService ;)

I hope this solution will help you ;). If it works I'll add this example on the website. 

See you,
Romain

**Comment by Romakita** [comment]
I’had just forgit to tell you that point. The start method is responsible to start http server. But in this example we override the original start method. So, you can trust me, the example will works without starting server and openning port. ;)

**Comment by Romakita** [comment]
Try and see ;)

**Comment by Romakita** [comment]
This code run the minimal lifecycle without running the entire process :)

**Comment by sasidhar-d** [comment]
Followed your approach, I think we are almost there. But `$onCronReady` function is never fired.

 I tried to put a break point at https://github.com/Romakita/ts-express-decorators/blob/master/packages/common/src/di/services/InjectorService.ts#L471 and I couldn't tell if any my services are being called there or not. The built-in services are iterated, but the custom ones I am not sure. Do they have a name attribute or something so that I can see if they are actually iterated over or not?

From what I can tell, the services I wrote were not iterated over.

**Comment by Romakita** [comment]
Hello @sasidhar-d 
I've added a working example on https://github.com/Romakita/example-ts-express-decorator/tree/4.0.0/example-mongoose-cron

See you :)

**Comment by Romakita** [comment]
https://github.com/Romakita/example-ts-express-decorator/blob/4.0.0/example-mongoose-cron/src/CronJob.ts

**Comment by sasidhar-d** [comment]
@Romakita Sorry, I was quite busy and couldn't check your examples. I executed the examples you have given as is.
 I do not see the log `========> CRON`
The emit of `$onCronReady` doesn't run the hooks in the services.
At this point I am ok with using a solution that doesn't look as elegant either.  How do I get the reference of a service after [this line](https://github.com/Romakita/example-ts-express-decorator/blob/4.0.0/example-mongoose-cron/src/CronJob.ts#L15).

If I can get the reference of the service with all the dependencies injected, I can manually call the methods necessary. Really appreciate all your help @Romakita you rock.

**Comment by Romakita** [comment]
Hello @sasidhar-d 
I've fixed this issue with v4.31.13. Now the example works fine  and the hook is correctly called :D 

See you ;)

**Comment by sasidhar-d** [comment]
@Romakita  That worked like a charm. Thanks, now this is working properly.
