### ISSUE TITLE
Wont compile on version 4.17.4

### ISSUE THREAD

**Issue by milewski** [Romakita/ts-express-decorators#363]
After upgrading from version `4.17.3` to `4.17.4` a project that depends on my project stop working totally due to this error:

```
error  in /Users/milewski/Code/backend/node_modules/@tsed/common/lib/filters/index.d.ts

(17,15): Could not find a declaration file for module './registries/FilterRegistry'. '/Users/milewski/Code/backend/node_modules/@tsed/common/lib/filters/registries/FilterRegistry.js' implicitly has an 'any' type.
    Try `npm install @types/tsed__common` if it exists or add a new declaration (.d.ts) file containing `declare module 'tsed__common';`

error  in /Users/milewski/Code/backend/node_modules/@tsed/common/lib/mvc/index.d.ts

(14,15): Could not find a declaration file for module './registries/MiddlewareRegistry'. '/Users/milewski/Code/backend/node_modules/@tsed/common/lib/mvc/registries/MiddlewareRegistry.js' implicitly has an 'any' type.
    Try `npm install @types/tsed__common` if it exists or add a new declaration (.d.ts) file containing `declare module 'tsed__common';`

```

found this might be the cause: https://github.com/Microsoft/TypeScript/issues/5711

**Comment by milewski** [comment]
building the project `ts-express-decorators` locally i get these errors (might be related):

```bash
[14:18:48] Using gulpfile ~/Code/ts-express-decorators/gulpfile.js
[14:18:48] Starting 'build'...
[14:18:48] Starting 'copy:files'...
[14:18:48] Finished 'copy:files' after 36 ms
[14:18:48] Starting 'tsc'...
error TS6059: File '/Users/milewski/Code/ts-express-decorators/dist/packages/common/src/di/interfaces/IProvider.ts' is not under 'rootDir' '/Users/milewski/Code/ts-express-decorators/src/'. 'rootDir' is expected to contain all source files.
error TS6059: File '/Users/milewski/Code/ts-express-decorators/dist/packages/common/src/di/interfaces/ProviderType.ts' is not under 'rootDir' '/Users/milewski/Code/ts-express-decorators/src/'. 'rootDir' is expected to contain all source files.
src/common/filters/registries/FilterRegistry.ts(12,14): error TS4023: Exported variable 'FilterRegistry' has or is using name 'IProvider' from external module "/Users/milewski/Code/ts-express-decorators/src/common/di/interfaces/IProvider" but cannot be named.
src/common/filters/registries/FilterRegistry.ts(12,14): error TS4023: Exported variable 'FilterRegistry' has or is using name 'Registry' from external module "/Users/milewski/Code/ts-express-decorators/src/core/class/Registry" but cannot be named.
src/common/mvc/registries/MiddlewareRegistry.ts(13,14): error TS4023: Exported variable 'MiddlewareRegistry' has or is using name 'Registry' from external module "/Users/milewski/Code/ts-express-decorators/src/core/class/Registry" but cannot be named.
TypeScript: 2 options errors
TypeScript: 3 declaration errors
TypeScript: 3 emit errors
TypeScript: emit failed
[14:18:53] Finished 'tsc' after 4.36 s
[14:18:53] Starting 'copy:src'...
[14:18:53] Finished 'copy:src' after 736 ms
[14:18:53] Starting 'copy:packages'...
[14:18:53] Starting 'write-pkg'...
[14:18:53] Starting 'copy:readme'...
[14:18:53] Copy src package 'ajv'
[14:18:53] Copy lib package 'ajv'
[14:18:53] Copy views 'ajv'
[14:18:53] Copy src package 'common'
[14:18:53] Copy lib package 'common'
[14:18:53] Copy views 'common'
[14:18:53] Copy src package 'core'
[14:18:53] Copy lib package 'core'
[14:18:53] Copy views 'core'
[14:18:53] Copy src package 'mongoose'
[14:18:53] Copy lib package 'mongoose'
[14:18:53] Copy views 'mongoose'
[14:18:53] Copy src package 'multipartfiles'
[14:18:53] Copy lib package 'multipartfiles'
[14:18:53] Copy views 'multipartfiles'
[14:18:53] Copy src package 'servestatic'
[14:18:53] Copy lib package 'servestatic'
[14:18:53] Copy views 'servestatic'
[14:18:53] Copy src package 'socketio'
[14:18:53] Copy lib package 'socketio'
[14:18:53] Copy views 'socketio'
[14:18:53] Copy src package 'swagger'
[14:18:53] Copy lib package 'swagger'
[14:18:53] Copy views 'swagger'
[14:18:53] Copy src package 'testing'
[14:18:53] Copy lib package 'testing'
[14:18:53] Copy views 'testing'
[14:18:53] Finished 'write-pkg' after 32 ms
[14:18:54] Finished 'copy:readme' after 484 ms
^CRafaels-iMac:ts-express-decorators milewski$ 

```

**Comment by Romakita** [comment]
Arg, gulp task doesn't emit the compilation error.

**Comment by Romakita** [comment]
what is your typescript version ?

**Comment by milewski** [comment]
```2.8.3```

**Comment by milewski** [comment]
works with version `4.17.6` thanks 👍
